language: ruby
rvm:
  - 2.0.0
env:
  - DB=mysql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake test
  - rspec --format nested
before_script:
  - cp config/database.yml.tpl config/database.yml
  - RAILS_ENV=test bundle exec rake db:create
bundler_args: --binstubs=./bundler_stubs
